import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const inputPath = path.resolve(__dirname, "../../openapi.yaml");
const outputPath = path.resolve(__dirname, "../src/generated/api-types.ts");
const checkMode = process.argv.includes("--check");

function withBanner(source) {
  return [
    "// This file is auto-generated by scripts/generate-types.mjs.",
    "// Do not edit manually.",
    "",
    source.trim(),
    "",
  ].join("\n");
}

async function main() {
  const ast = await openapiTS(pathToFileURL(inputPath));
  const generated = withBanner(astToString(ast));

  let current = "";
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    current = "";
  }

  if (checkMode) {
    if (current !== generated) {
      throw new Error(
        `Generated types are stale: ${path.relative(process.cwd(), outputPath)}`,
      );
    }
    return;
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated, "utf8");
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
